"""rename department

Revision ID: bf9a4d4e3bbf
Revises: ac0b03361d5a
Create Date: 2025-06-20 13:24:39.251956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf9a4d4e3bbf'
down_revision = 'ac0b03361d5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
